Update OpenAPI Schema's file path in README.md
RedHatInsights/config-manager pull request #134
Opened 2023-09-28 06:57 UTC by upadhyeammit

2023-10-23 11:58 UTC, kgaikwad requested changes
Change looks good to me but jobs are not happy, failed with errors.  Please look into failures.

2023-10-25 17:03 UTC, subpop commented
These tests sometimes fail. I have not looked into why, but I have found that rerunning the test often ends up succeeding.

```
{"level":"error","error":"Get \"http://localhost:56998/api/inventory/v1/hosts?fields%5Bsystem_profile%5D=rhc_client_id%2Crhc_config_state&filter%5Bsystem_profile%5D%5Brhc_client_id%5D=not_nil&page=1&registered_with=cloud-connector\": dial tcp [::1]:56998: connect: connection refused","time":"2023-09-28T06:58:50Z","message":"error during request to inventory"}
```

2023-10-25 17:04 UTC, subpop commented
The *Lint commits* workflow checks commits for conformance to the [Conventional Commits](https://www.conventionalcommits.org/) format.

2024-02-01 12:21 UTC, kgaikwad approved these changes

2024-02-01 12:23 UTC, merged